### ISSUE TITLE
Trouble with branch simualtions

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#19]
I'm having trouble getting exact restart tests that test: restart, branch, and hybrid startups. It seems to be failing doing the branch type. I've tried various lengths up to 10months or 120 days.

Here's a list of tests that fail:

ERI_D_Ld120.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850		
ERI_D_Ld60.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850		
ERI_D_Ld90.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850
ERI_D_Lm10.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850		
ERI_D_Lm3.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850		
ERI_D_Lm6.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850

some of the above fail because of the run length.

**Comment by ekluzek** [comment]
The ERI test does the full length, and then the hybrid start, and then the branch. Since it's failing at the branch step that shows the hybrid part was fine. So it really is a problem with the branch startup. I checked and these fail at the branch step. I think the other two fail because of run length.

	RUN_TYPE: branch
ERI_D_Ld120.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850.GC.slim-n1_cesm21chlist
	RUN_TYPE: branch
ERI_D_Ld60.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850.GC.slim-n1_cesm21chintelasl
	RUN_TYPE: branch
ERI_D_Ld90.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850.GC.slim-n1_cesm21chlist
	RUN_TYPE: branch

@marysa is a branch startup type something that you care about at all? The main reason for it is if you want to reproduce a simulation you already ran -- but change history output for a segment of it.

**Comment by marysa** [comment]
Hmm. Yes it would be nice, but not absolutely necessary. If it isn't clear why it doesn't work / will be too hard to fix, then just having a note that "hey, you can't do a branch run, make sure you've asked for all the history variables you want otherwise you'll have to run from the start again" would be fine!

**Comment by ekluzek** [comment]
I think we might put that warning in place to start off with. We will need to fix it eventually. But, it's good to know it isn't critical right now.

**Comment by slevisconsulting** [comment]
We will fix #14 first.

**Comment by ekluzek** [comment]
The branch part of this is working now, we have a related issue with the hybrid part
