### ISSUE TITLE
Replace perl based build-namelist with simpler cime/python based version

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#23]
There isn't a reason to keep the existing perl based build-namelist infrastructure the end result of SLIM will be a really simple namelist and there's no need to keep in sync with the CTSM version. So once we simplify the namelist we should replace it with a CIME-based python version that will be very simple.

**Comment by marysa** [comment]
agree!!! I haven't kept up with the latest changes to how CESM builds, but there is no reason to keep the old way for this!

**Comment by ekluzek** [comment]
I've got a protype start to this in #31. There's some simplification to the XML variables that I'd like to suggest.

Currently we have the CLM set:

	CLM_CONFIG_OPTS:
	CLM_USE_PETSC: 
	CLM_ACCELERATED_SPINUP: 
	CLM_BLDNML_OPTS: 
	CLM_CO2_TYPE: 
	CLM_FORCE_COLDSTART: 
	CLM_NAMELIST_OPTS: 
	CLM_NML_USE_CASE:

The first three don't make sense anymore. The last ones I suggest changing to:

SLIM_SCENARIO: global_uniform, 1850_control, 2000_control
SLIM_CO2_TYPE
SLIM_NAMELIST_OPTS
SLIM_START_TYPE: default, cold, arb-ic

SLIM_CO2_TYPE will work just as before as for CLM_CO2_TYPE. SLIM_NAMELIST_OPTS will work as before as well, although I predict it will seldom be used. But, we sometimes find it important for setting up compsets in CESM, so I think we should keep it.

Note, if you set RUN_REFCASE, but change SLIM_START_TYPE that will register as a contradiction and it will error out.

**Comment by ekluzek** [comment]
@marysa once I have a prototype of this we should meet with the group to go over how it will work. This is something we should hear from as many people using SLIM as we can.
