### ISSUE TITLE
Remove gridcell subgrid infrastructure

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#24]
From the notes from @marysa and Isla at the bottom of the document on requirements for SLIM here

https://docs.google.com/document/d/1NxoykN0NY5kFoSmO_dSvdw-1I5VD0q6qHwGn6_RoPtc/edit#heading=h.b374lh72xly7

I can see that the subgrid infrastructure for CLM doesn't help SLIM and only adds complexity. I think the gridcell level infrastructure is helpful, as decomposing into a single vector is a really useful thing for parallelism. But, we could remove a lot of infrastructure and complexity if the landunit, column, patch subgrid level type handling was just removed. This also means that many of the subgrid modules can be removed or at least vastly simplified. It also means that there might be very little code that would need to maintain it's connection to CLM.

There will be some code that's duplicated, like histFile and ncdio_pio, accumulMod, but I think that duplication will be acceptable. Changes in those codes for CLM likely won't need to come into SLIM. There will also be code that will have the same name right now, but highly modified for SLIM so there will be no need to maintain a connection to CLM code.

So gridcell loops and data would remain. But, landunit, column, and patch should be able to be removed.

**Comment by slevisconsulting** [comment]
Completed this work in #63
