### ISSUE TITLE
Keep multiple instance capability in SLIM?

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#34]
I mainly pose this as a question. The code currently has some additional complexity to handle the ability to have more than one instance running at the same time. My inclination is to leave it in for now (and @fischer-ncar agrees), so we don't have to add it back in again later. But, I probably won't test it until we do think it might be useful. There are times when using multiple instances helps in surprising ways, so it could be good to have. But, I'm opening this issue to hold the discussion on this.

@marysa

**Comment by marysa** [comment]
If it isn't a pain to leave it, I'd vote to leave it, though I've never used it for CLM either and don't have a great grasp of what it could be used for (unless you can have multiple lands running with different forcings, or reading different surface data files... there is nothing intrinsically chaotic about the land and especially not about slim, so just running a bunch of "slightly perturbed" lands at the same time doesn't make sense to me)

**Comment by ekluzek** [comment]
You can change any of the namelist items for SLIM with multi-instance. So you could run different surface datasets. You couldn't easily change the forcing (at least from datm), but you could change namelist items for CAM, so have the forcing from the atmosphere perturbed there.

Anyway, I'll try to keep it around. We won't have a ton of testing for it, but I will try to not break it.

**Comment by marysa** [comment]
Got it. Sounds good - I don't feel strongly about it!

**Comment by ekluzek** [comment]
Closing this as a wontfix for something we aren't planning on working on. We are leaving the code in place, so could work on it in the future.
