### ISSUE TITLE
Add metadata to mml_surdat files, ideally using a mksurdat tool than can also generate such files

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#36]
We need to add metadata to the mml_surdat files so that the quantities and units for each variable is more clearly defined. We should use the CF standards for defining the files. Right now the files just have the variable names as follows:

dimensions:
	time = 12 ;
	lsmlat = 96 ;
	lsmlon = 144 ;
variables:
	double alb_snf(time, lsmlat, lsmlon) ;
	double bucketdepth(time, lsmlat, lsmlon) ;
	double alb_svd(time, lsmlat, lsmlon) ;
	double soil_type(time, lsmlat, lsmlon) ;
	double alb_svf(time, lsmlat, lsmlon) ;
	double alb_gvd(time, lsmlat, lsmlon) ;
	double snowmask(time, lsmlat, lsmlon) ;
	double alb_gvf(time, lsmlat, lsmlon) ;
	double roughness(time, lsmlat, lsmlon) ;
	double soil_tk_2d(time, lsmlat, lsmlon) ;
	double alb_gnd(time, lsmlat, lsmlon) ;
	double alb_gnf(time, lsmlat, lsmlon) ;
	double glc_tk_2d(time, lsmlat, lsmlon) ;
	double soil_cv_2d(time, lsmlat, lsmlon) ;
	double glc_mask(time, lsmlat, lsmlon) ;
	double glc_cv_2d(time, lsmlat, lsmlon) ;
	double evap_res(time, lsmlat, lsmlon) ;
	double emissivity(time, lsmlat, lsmlon) ;
	double lsmlon(lsmlon) ;
	double lsmlat(lsmlat) ;
	int64 time(time) ;
	double alb_snd(time, lsmlat, lsmlon) ;

longnames, and units and other standard attributes: mode, bounds, calendar, axis, and coordinates. And global attributes: references, title, institution, Conventions, comment, history, and things like the user who created and how.

CF conventions are here:

https://cfconventions.org/

**Comment by ekluzek** [comment]
This is an important thing to do for the CESM2_3 branch version when SLIM becomes an official part of CESM.

**Comment by slevisconsulting** [comment]
1) @marysa is there a tool for generating the SLIM surface datasets where we could add the metadata, or should we start from scratch with a new such tool?

2) We need to come up with the list of metadata that we want on the file.

**Comment by slevisconsulting** [comment]
This surdat file
`/glade/p/cesmdata/inputdata/lnd/slim/surdat/slim2deg_fromCMIP6-AMIP-1deg_ensemble001-010_1991to2010clim_max-ctrl-bucket_rs150_c20210401.nc`
contains metadata.

**Comment by slevisconsulting** [comment]
May want to rename this new tool (for making SLIM surdat files) from mksurdat to something else because it's mainly averaging ctsm history files.

@marysa it's probably worth sharing your code with me even just to make sure that I develop something similar that works correctly. Or if you have something more complete, I could finalize it.

@islasimpson if you have any input on this, please share.
