### ISSUE TITLE
Remove use_cn and BGC compsets

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#50]
I've been nervous about removing the use_cn part of the code, since it's something that's actually in and used in the clm_driver for SLIM. There are also BGC specific compsets, so I thought that might be meaningful. I also was concerned that dust emissions might be handled differently for use_cn on, verses not because of how the dust code works, especially if it's still using data from the initial conditions. In talking with @marysa we found this wasn't the case, and that the mml_surdat dataset includes dust emission and uses it to be sent from SLIM to ATM. As such it should be perfectly safe to remove use_cn and BGC compsets.

To verify this and make sure that there wasn't some strange dependency in SLIM that wasn't obvious I ran a test to make sure this is true. If dust emissions are different it might only show up on some fields, so it's best to have this coupled to CAM to ensure nothing strange is happening.

So I ran the case: SMS_Lm13.f19_g16.H_MML_2000_CAM5_BGC.cheyenne_intel.clm-global_uniform_g16_SOMMonthly and compared to SMS_Lm13.f19_g16.H_MML_2000_CAM5.cheyenne_intel.clm-global_uniform_g16_SOMMonthly for the tag: slim0.1.005_release-cesm2.1.4 and found that the files compare exactly other than some differences in the list of fields.

To check for other differences I also then reran the BGC case with the following...

``` bash
./xmlchange --force CLM_CO2_TYPE="constant"
./xmlchange --force CLM_BLDNML_OPTS="-bgc bgc"
./xmlchange --force CLM_CONFIG_OPTS="-phys clm5_0"
./xmlchange --force CCSM_BGC="none"
```
and found that they still remain the same. The above means that differences in CO2, and physics versions don't matter to SLIM, which is good to know.

**Comment by marysa** [comment]
Phew, that's a relief that it is working as expected!
