### ISSUE TITLE
Update the MML_* history fields to remove the MML_ part

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#54]
After we have removed the CLM fields from SLIM, we should rework the MML_* history fields to remove the MML_ part of the name. Possibly some of the names should be changed so they better reflect what is going on in SLIM.

**Comment by ekluzek** [comment]
As part of this we should make sure the fields are default active as they should be. That part is pretty high priority. Removing the MML_* part when it doesn't conflict with other code would also be really helpful for users.

**Comment by slevisconsulting** [comment]
Once this is addressed, I will need to generate new baselines.

**Comment by slevisconsulting** [comment]
Removing mml from all history field names and their long descriptions.

Follow-up questions:
1) Remove mml from variable names?
2) Remove mml from examples like this?
`call hist_addfld2d (fname='soilz', units='m',  type2d='mml_lev', ..., mml_dim=mml_nsoi)`
I.e., from mml_lev, mml_dim, mml_nsoi?

I'm leaning against 1 and 2 above for now OR I would replace mml with slim. We may find it helpful to maintain a distinction from the bit of clm code that hasn't been removed, yet.

**Comment by ekluzek** [comment]
Hmmm good question. I suggest as a first step you just change the output history names and then run baselines and bring that in as one thing. That will establish that the name change doesn't change answers although it will appear so in the baselines.

After that is done you can then do the more extensive internal changes to change  variable names and then ensure those changes are bit for bit with the baselines. So the internal changes can be ensured they are identical.
