### ISSUE TITLE
Add capability for surface characteristics to change in time

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#9]
This is something I'm adding because in discussions with @marysa this would be useful in the future. We don't think it's needed anytime soon. But it could be useful.

**Comment by ekluzek** [comment]
In thinking about implementing this I wonder if moving the mml_surdat file into the streams file format would be a good way to go here. That would allow not only change in time -- but interpolation to different resolutions.

**Comment by marysa** [comment]
Oh really? It does interpolation for you, too? That could be very useful. Any drawbacks to the streams approach? (other than the fact that I'm more used to messing the user_nl_clm, but I'm sure I can get used to playing with a streams file instead!)

**Comment by ekluzek** [comment]
I only see positives for making the change. You'll have greater control and flexibility, and it'll be using shared code that isn't custom for just SLIM. So there's more confidence in it because of a larger user and developer base. And it lowers maintenance cost of SLIM because it's outside of the SLIM code. There's options to control how the time averaging is done, as well as the spatial interpolation and for doing things like fill. The only downside is that there will be time to make the conversion. And as you say the control variables will look differentl.

Now the other caveat is that if we do decide this is the way to go likely we want to do this in the NUOPC version of the SLIM in the latest CESM2_3_beta06 version where NUOPC is the default. So I think we should hold off on doing it until SLIM is updated.

**Comment by marysa** [comment]
Sounds good. Had to google "NUOPC"!

**Comment by ekluzek** [comment]
We do think this would be a useful capability, however I'm going to close this as a wontfix for now.
